import {
  Sun,
  LayoutPanelTop,
  Layers,
  Link2,
  Zap,
  Bookmark,
  FileText,
  Armchair,
  Paintbrush,
  ShoppingBag,
  Building2,
  Palette,
  HardHat,
  Wrench,
  Users,
  FileInput,
  Calculator,
  Smartphone,
  Bot,
  Wind,
  Cable,
  Languages,
} from "lucide-react";

// Content follows .claude/skills/truebex-brand-voice:
// - Truebex is its own platform. Never name or compare to other software or
//   engines.
// - Lead with what is distinctive; skip table-stakes features every design
//   tool has.
// - Claims must be true of the shipping app; planned work goes in ROADMAP.

export const SITE = {
  name: "Truebex",
  url: "https://truebex.com",
  tagline: "True Building Experience",
  title: "Truebex — See It Before You Build It",
  description:
    "Truebex is a building design platform where daylight is measured through every opening, surfaces design themselves, and one change updates the whole project — instantly.",
  email: "dr99tm@gmail.com",
} as const;

// Absolute hrefs (/#section, not #section) so the links work from any route,
// not just the homepage. From /dashboard/ a bare #features would resolve to
// /dashboard/#features (no such section); /#features navigates home first.
export const NAV_LINKS = [
  { label: "Product", href: "/#features" },
  { label: "How It Works", href: "/#how-it-works" },
  { label: "Who It's For", href: "/#who-its-for" },
  { label: "Pricing", href: "/#pricing" },
  { label: "Developers", href: "/developers/" },
  { label: "FAQ", href: "/#faq" },
  { label: "Contact", href: "/#contact" },
] as const;

export const FEATURES = [
  {
    id: "daylight",
    icon: Sun,
    title: "Daylight, measured — not painted",
    description:
      "Every window and door reads the sky and sun on its far side and lets exactly that light into the room. Open a door between a bright room and a dark one, and the light follows.",
  },
  {
    id: "fills",
    icon: LayoutPanelTop,
    title: "Surfaces that design themselves",
    description:
      "Split any wall into panels and fill them with rule-based patterns — start, end, centre, alternating. They re-flow on their own when the wall grows, shrinks or gains an opening.",
  },
  {
    id: "assets",
    icon: Layers,
    title: "Make it once, update everywhere",
    description:
      "Save a finished wall face as an asset and place it anywhere. Open the asset, change it, and every copy across the project updates in one step.",
  },
  {
    id: "intent",
    icon: Link2,
    title: "Design intent that holds",
    description:
      "Offsets, links, locked dimensions and reference planes keep shapes in relationship while the walls they belong to move and resize.",
  },
  {
    id: "instant",
    icon: Zap,
    title: "Instant at any size",
    description:
      "An edit costs only what it changes. Moving a wall in a full building takes milliseconds — 240 ms became 4.3 ms in our benchmark — so the model never lags behind your idea.",
  },
  {
    id: "memory",
    icon: Bookmark,
    title: "A project that remembers its light",
    description:
      "Lighting setups and the exact view — camera, section, storey — are saved inside the project, and every lighting change can be undone like any other edit.",
  },
  {
    id: "sheets",
    icon: FileText,
    title: "Drawings that draw themselves",
    description:
      "One command lays out plans, sections, stair sheets and schedules, with forms you fill once. Export a vector PDF with selectable text and fillable fields, or DXF.",
  },
  {
    id: "objects",
    icon: Armchair,
    title: "Doors, cabinets and stairs from numbers",
    description:
      "Describe a door, a window, a cabinet or a stair by its parameters and it builds itself, regenerates with its host, and keeps its handles and hardware in place.",
  },
  {
    id: "finishes",
    icon: Paintbrush,
    title: "Finishes on any face",
    description:
      "Paint, wallpaper and three-dimensional patterns on walls, floors, ceilings and models, driven by the same panel system — with mouldings that stop at door jambs and follow curved walls.",
  },
] as const;

// Where the platform is going. Shown as "on the roadmap", never as shipped.
export const ROADMAP = [
  {
    icon: FileInput,
    title: "Works with IFC and DWG",
    description: "Exchange models and drawings with every other tool on the project.",
  },
  {
    icon: Users,
    title: "Your team on one model",
    description: "Several people in one project, with every change in a history you can rewind.",
  },
  {
    icon: Calculator,
    title: "The model prices itself",
    description: "Real products with live prices and stock, by region, so the bill of quantities updates as you draw.",
  },
  {
    icon: Smartphone,
    title: "On your phone and in a headset",
    description: "Panoramas rendered in the cloud, refreshed the moment anything changes, and edits from wherever you are.",
  },
  {
    icon: Wind,
    title: "Daylight, energy, sound and wind reports",
    description: "Measured results from the one true model, on demand or as you work.",
  },
  {
    icon: Cable,
    title: "Building services",
    description: "Ducts, pipes and circuits that route and size themselves.",
  },
  {
    icon: Bot,
    title: "An assistant that edits the model",
    description: "Ask for a window on the north wall and it appears, with the light measured and the change undoable.",
  },
  {
    icon: Languages,
    title: "Arabic, right to left",
    description: "The whole app in Arabic, with metric and imperial units.",
  },
] as const;

// The one capture the site shows (clean frames only — no HUD or labels).
export const PRODUCT_SHOT = {
  src: "/images/product/daylight-doorway.jpg",
  wide: "/images/product/daylight-doorway-wide.jpg",
  alt: "Soft daylight falling through a doorway into a quiet white room, designed and lit in Truebex",
  caption: "Daylight measured through a doorway — captured in Truebex.",
  width: 1600,
  height: 1196,
} as const;

export const STEPS = [
  {
    number: "01",
    title: "Draw the plan",
    description:
      "Lay out walls, rooms and openings. The building forms in 3D with every line.",
  },
  {
    number: "02",
    title: "Shape the surfaces",
    description:
      "Panel the walls and set fill rules. Patterns arrange themselves and keep up with every change.",
  },
  {
    number: "03",
    title: "Let the light in",
    description:
      "Daylight is measured through every opening, room by room, as you design.",
  },
  {
    number: "04",
    title: "Make it reusable",
    description:
      "Save what works as an asset. Change it once and the whole project follows.",
  },
] as const;

export const AUDIENCES = [
  {
    icon: Building2,
    title: "Architects",
    description:
      "Judge daylight and proportion while you draw — not weeks later.",
  },
  {
    icon: Palette,
    title: "Interior Designers",
    description:
      "Panels, fills and finishes that adapt when the room changes.",
  },
  {
    icon: HardHat,
    title: "Developers & Contractors",
    description:
      "One asset, placed across every unit, updated in one step.",
  },
  {
    icon: Wrench,
    title: "Engineers",
    description:
      "References and constraints that keep relationships intact as the design evolves.",
  },
  {
    icon: Users,
    title: "Clients & Stakeholders",
    description:
      "See the real light in the real room before anything is built.",
  },
] as const;

export const PRICING_PLANS = [
  {
    id: "free",
    name: "Free",
    price: "$0",
    period: "",
    description: "Explore Truebex and build against the developer API.",
    features: [
      "Plan and 3D design in one model",
      "Measured daylight",
      "Dynamic surface fills",
      "Developer API: 1,000 requests / month",
      "2 API keys",
    ],
    cta: "Create free account",
    href: "/signup/",
    highlighted: false,
  },
  {
    id: "pro",
    name: "Pro",
    price: "$99",
    period: "/month",
    description: "For professionals who design and present every day.",
    features: [
      "Everything in Free",
      "Full lighting suite: ray tracing and path tracing",
      "Asset library that updates everywhere",
      "Developer API: 100,000 requests / month",
      "20 API keys",
      "Priority support",
    ],
    cta: "Upgrade to Pro",
    href: "/dashboard/billing/?plan=pro",
    highlighted: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: "Custom",
    period: "",
    description: "For teams and organisations designing at scale.",
    features: [
      "Everything in Pro",
      "Team onboarding",
      "Custom asset libraries",
      "High-volume API limits",
      "Dedicated contact",
    ],
    cta: "Contact us",
    href: "/#contact",
    highlighted: false,
  },
] as const;

// The ideas Truebex is built on (shown in the "Why Truebex" section).
export const PRINCIPLES = [
  {
    title: "Truth, not decoration",
    description:
      "What you see is computed from the sun, the sky and the openings you placed — not dressed up afterwards.",
  },
  {
    title: "Intent survives change",
    description:
      "Relationships, dimensions and patterns hold while the design moves around them.",
  },
  {
    title: "Make it once",
    description:
      "Every good detail becomes an asset you can place, refine and update everywhere at once.",
  },
] as const;

export const FAQS = [
  {
    q: "What is Truebex?",
    a: "Truebex is a building design platform for Windows. You draw in plan and design in 3D at the same time, with daylight measured through every opening, surfaces that arrange themselves, and assets that update everywhere when you change them.",
  },
  {
    q: "How is the lighting in Truebex different?",
    a: "Each window and door measures the sky and sun outside it and lets that exact amount of light into the room. Move a window, widen a door or add a wall, and the light in every room responds — including rooms that only receive light through another room.",
  },
  {
    q: "What are dynamic surface fills?",
    a: "Patterns that understand the surface they sit on. You set the rules — what goes at the start, the end, the centre or in between — and Truebex lays them out, re-flowing them whenever the wall or its openings change.",
  },
  {
    q: "What happens when I edit an asset?",
    a: "Open any saved asset, change it, and save. Every copy placed across the project updates in a single step, so a detail is only ever designed once.",
  },
  {
    q: "What do I need to run Truebex?",
    a: "A Windows PC with a modern graphics card. An NVIDIA RTX card unlocks the highest lighting quality, including ray tracing and path tracing.",
  },
  {
    q: "Is there an API for developers?",
    a: "Yes. Create API keys in your dashboard and call the Truebex API with a bearer token. Every plan includes a monthly request allowance; see the developer docs.",
  },
  {
    q: "Does Truebex work with IFC and DWG files?",
    a: "Today Truebex exports vector PDF and DXF. IFC and DWG import and export are on the roadmap, together with sharing a project with your team.",
  },
  {
    q: "How can I pay?",
    a: "Pro plans are billed monthly by card. Payments are rolling out; the pricing section shows the plans.",
  },
] as const;

// The Download page (/download/) and the dashboard's Download panel. The
// version, size and date come from src/content/releases.json (saved by
// `npm run sync:releases` from the release feed), never typed here.
export const DOWNLOAD = {
  metaTitle: "Download Truebex for Windows",
  description:
    "Download Truebex for Windows: the building design platform with measured daylight. The installer needs no account; a free account holds your licence.",
  eyebrow: "Download",
  h1: "Download Truebex for Windows",
  intro:
    "One installer for Windows. Downloading needs no account, and every download is a signed release whose size and checksum are listed here.",
  cta: "Download for Windows",
  ctaBeta: "Download the beta",
  preparing: "Preparing your download…",
  noRelease: "The installer is published here with each release. Check back soon.",
  offline: "We can't reach the download server right now. Please try again in a moment.",
  version: "Version",
  released: "Released",
  size: "Size",
  checksum: "SHA-256",
  beta: "Beta",
  requirementsTitle: "What you need",
  requirements: [
    "A Windows 10 or Windows 11 PC (64-bit).",
    "A modern graphics card. A card with hardware ray tracing unlocks the highest lighting quality, including ray tracing and path tracing.",
    "About 450 MB of disk space for the installed app.",
  ],
  accountTitle: "Your licence lives in your account",
  accountText:
    "A free Truebex account holds your plan and the computers you use it on, so you can see and remove them from your dashboard.",
  accountCta: "Create a free account",
  changelogCta: "See what's new",
} as const;

// The Changelog page (/changelog/): one section per release from the feed,
// with the release's version as its anchor (#1.1.0, the manifest's notes_url).
export const CHANGELOG_PAGE = {
  metaTitle: "Changelog",
  description:
    "Every Truebex release and what changed in it, newest first: notes for each version of the building design platform for Windows, with a link to download.",
  eyebrow: "Changelog",
  h1: "What's new in Truebex",
  intro: "Every release of Truebex for Windows, newest first.",
  empty: "Release notes appear here with each release.",
  release: "Truebex",
  beta: "Beta",
  downloadCta: "Download the latest release",
} as const;

// Marketplace pages (PF7): the checkout page an order sent from the app opens,
// the buyer's orders and requests, and the admin tools. The marketplace itself
// stays in ROADMAP until roadmap 40 ships it; these pages only serve orders
// and requests for quote that were sent from Truebex.
export const MARKET = {
  states: {
    awaiting_payment: "Awaiting payment",
    paid: "Paid",
    pending: "Waiting for the supplier",
    accepted: "Accepted",
    rejected: "Declined by the supplier",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    submitted: "Sent to the supplier",
    quoted: "Quoted",
    declined: "Declined by the supplier",
    expired: "Expired",
  } as Record<string, string>,
  checkout: {
    metaTitle: "Checkout",
    h1: "Checkout",
    intro:
      "Review the order you sent from Truebex, then pay on the payment provider's secure page. Each supplier confirms and delivers its own part.",
    missing: "Open this page from the link Truebex gave you for your order.",
    signIn: "Sign in to see your order",
    loading: "Loading your order…",
    pay: "Pay",
    paying: "Opening the payment page…",
    placedTitle: "Order placed",
    placedText: "Payment received. Each supplier now confirms its part of the order.",
    confirming: "Confirming your payment…",
    stillConfirming: "Your payment is still being confirmed. This page shows it as soon as it is.",
    cancelledPayment: "Payment was cancelled. Nothing was charged.",
    notPayable: "This order has nothing left to pay.",
    quote: "This is a request for quote: each supplier replies with its price. Accept a quote from your orders.",
    secure: "Card details are entered on the payment provider's page. Truebex never sees them.",
    deliveryTo: "Delivery to",
    contact: "Contact",
    products: "Products",
    delivery: "Delivery",
    deliveryDays: "Delivery in {min}–{max} days",
    taxIncluded: "Includes tax",
    tax: "Tax",
    total: "Total",
    qty: "Qty",
    each: "each",
    quoted: "Quoted",
    ordersLink: "See all your orders",
  },
  orders: {
    title: "Orders",
    description: "Orders and requests for quote sent from Truebex, with each supplier's progress.",
    empty: "No orders yet. Orders and requests for quote you send from Truebex appear here.",
    order: "Order",
    quote: "Request for quote",
    project: "Project",
    pay: "Pay now",
    accept: "Accept quote",
    cancel: "Cancel",
    confirmCancel: "Cancel this order? Suppliers that have not accepted it yet will not deliver.",
    validUntil: "Quote valid until",
    expires: "Expires",
    paidOffline: "Each supplier invoices you directly for this order.",
    fromQuote: "From your accepted quote",
  },
  admin: {
    title: "Marketplace",
    description: "Suppliers, the product review queue, reviews, orders, commissions and feed runs.",
    tabs: {
      suppliers: "Suppliers",
      products: "Products",
      reviews: "Reviews",
      orders: "Orders",
      commissions: "Commissions",
      feeds: "Feeds",
    },
    paymentsOff: "Card payments for orders are off (MARKET_PAYMENTS_ENABLED): every supplier takes requests for quote only.",
    paymentsOn: "Card payments for orders are on.",
    paymentsNoStripe: "Card payments for orders are switched on, but Stripe is not configured on this server (STRIPE_SECRET_KEY): Pay answers 503.",
    verify: "Verify",
    suspend: "Suspend",
    reinstate: "Reinstate",
    commission: "Commission (basis points)",
    save: "Save",
    connect: "Payout onboarding link",
    application: "Application",
    applicationNone: "No application: this supplier was created by an admin.",
    documents: "Documents",
    noDocuments: "No document uploaded yet.",
    approve: "Approve",
    reject: "Reject",
    withdraw: "Withdraw",
    reason: "Reason (shown to the supplier)",
    publish: "Publish",
    hide: "Hide",
    quoteFor: "Quote for the supplier",
    unitPrice: "Unit price (minor units)",
    deliveryFee: "Delivery fee (minor units)",
    makeStatements: "Make last month's statements",
    empty: "Nothing here.",
    statuses: {
      pending_review: "Waiting for review",
      approved: "Approved",
      rejected: "Rejected",
      withdrawn: "Withdrawn",
      hidden: "Hidden by a feed",
      all: "All",
      pending: "Pending",
      published: "Published",
    } as Record<string, string>,
  },
} as const;

// PF8: the supplier portal (/supplier/, noindex). Companies that sell
// furniture, finishes and fittings run their Truebex catalogue here. The
// marketplace itself stays in ROADMAP until roadmap 40 ships it in the app.
export const SUPPLIER = {
  meta: { title: "Supplier portal", template: "%s · Truebex Supplier portal" },
  nav: {
    overview: "Overview",
    catalogue: "Catalogue",
    prices: "Prices and stock",
    imports: "Imports",
    inbox: "Inbox",
    analytics: "Analytics",
    billing: "Plan and billing",
    team: "Team",
    switcher: "Supplier",
    dashboard: "Your account",
  },
  shell: {
    loading: "Loading the supplier portal…",
    unreachable: "We can't reach the Truebex server right now.",
    retry: "Try again",
    redirecting: "Redirecting to sign in…",
    noSupplierTitle: "You are not part of a supplier yet",
    noSupplierText:
      "Apply to sell on Truebex, or ask your company's owner on Truebex to invite this account by e-mail.",
    apply: "Apply as a supplier",
  },
  status: {
    applied: "Under review",
    verified: "Verified",
    suspended: "Suspended",
    declined: "Declined",
  } as Record<string, string>,
  roles: {
    owner: "Owner",
    catalogue: "Catalogue editor",
    orders: "Order handler",
    viewer: "Viewer",
  } as Record<string, string>,
  roleHelp: {
    owner: "Everything, including the plan, billing, team and keys.",
    catalogue: "Products, prices, stock and imports.",
    orders: "Requests for quote and orders.",
    viewer: "Reads the catalogue, prices and numbers.",
  } as Record<string, string>,
  signup: {
    metaTitle: "Apply as a supplier",
    h1: "Sell your products in Truebex",
    intro:
      "Designers place real products in their rooms and price their projects by region. Apply with your company details, the regions you deliver to and one company document; we verify every supplier before its products are listed.",
    signedOut: "Create a Truebex account or sign in first; your application is linked to it.",
    createAccount: "Create an account",
    signIn: "Sign in",
    steps: ["Company", "Regions and contact", "Document"],
    company: {
      name: "Trading name",
      nameHint: "As designers will see it, e.g. Nord Living.",
      legalName: "Legal name",
      country: "Country of registration (two letters, e.g. GB)",
      companyNumber: "Company number",
      vatId: "VAT number (optional)",
      website: "Website (https://…, optional)",
      line1: "Address",
      line2: "Address line 2 (optional)",
      city: "City",
      postcode: "Postcode (optional)",
      addressCountry: "Address country (two letters)",
    },
    regions: {
      title: "Where you deliver",
      help: "Each region has its own price list in its own currency. You can add regions later.",
      contactTitle: "Who we contact",
      contactName: "Name",
      contactEmail: "E-mail for orders and the decision",
      contactPhone: "Phone (optional)",
    },
    document: {
      title: "Company document",
      help: "One PDF of at most 10 MB: a certificate of incorporation, a trade licence or a VAT registration. Only Truebex's reviewers can open it.",
      choose: "Choose a PDF",
    },
    back: "Back",
    next: "Next",
    submit: "Send application",
    sending: "Sending…",
    reviewTitle: "Under review",
    reviewText:
      "We received your application and e-mailed a confirmation. We check the company details and the document, then e-mail you the decision. You can prepare your catalogue in the portal meanwhile; products are listed once you are verified.",
    addDocument: "Upload another document",
    documents: "Documents sent",
    openPortal: "Open the supplier portal",
    verifiedTitle: "You are a verified supplier",
    declinedTitle: "Your application was declined",
  },
  join: {
    metaTitle: "Join a supplier",
    h1: "Join your team on Truebex",
    intro: "Accept the invitation you received by e-mail. Sign in with the address it was sent to.",
    missing: "Open this page from the link in your invitation e-mail.",
    accept: "Accept invitation",
    accepting: "Joining…",
    done: "You joined {name}.",
  },
  overview: {
    title: "Overview",
    description: "Your catalogue, requests and orders at a glance.",
    underReview:
      "Your application is under review. Prepare products, prices and imports now; you can submit products for review once you are verified.",
    suspended: "This supplier is suspended. Its products are not listed. Contact Truebex.",
    openRequests: "Open requests for quote",
    openOrders: "Open orders",
    products: "Products",
    lastImport: "Last import",
    noImport: "No import yet.",
    week: "Last 7 days",
    impressions: "Search impressions",
    views: "Product views",
    placements: "Placements",
    quotes: "Requests for quote",
    orders: "Orders",
    feed: "Daily feed",
    noFeed: "No feed address registered.",
  },
  productStatus: {
    draft: "Draft",
    pending_review: "In review",
    approved: "Listed",
    rejected: "Changes needed",
    hidden: "Hidden",
    withdrawn: "Withdrawn",
    all: "All",
  } as Record<string, string>,
  catalogue: {
    title: "Catalogue",
    description: "Products with their variants, pictures and 3D files. New products are reviewed before they are listed.",
    newProduct: "New product",
    search: "Search name or SKU",
    empty: "No products yet. Add one here, or upload a spreadsheet under Imports.",
    submitDrafts: "Submit all drafts for review",
    submitted: "{n} submitted for review.",
    skipped: "{n} not ready: {skus}.",
    sku: "SKU",
    name: "Name",
    kind: "Kind",
    category: "Category",
    descriptionLabel: "Description",
    brand: "Brand (optional)",
    create: "Create draft",
    variants: "variants",
    kinds: {
      object: "Object (placed in rooms)",
      material: "Material",
      finish: "Finish (paint, wallpaper, tile)",
      theme: "Room theme",
    } as Record<string, string>,
  },
  product: {
    back: "All products",
    missing: "Open a product from the catalogue.",
    loading: "Loading the product…",
    details: "Details",
    save: "Save",
    saved: "Saved.",
    reviewNote: "Reviewer's note",
    reReview: "Changing the name, kind, category, pictures or 3D files of a listed product sends it back to review.",
    submit: "Submit for review",
    hide: "Hide",
    show: "Show again",
    discontinue: "Mark discontinued",
    withdraw: "Withdraw",
    confirmWithdraw: "Withdraw this product for good? Designers who placed it are offered similar products.",
    confirmDiscontinue: "Mark every variant discontinued? Designers who placed it keep its data and are offered similar products.",
    variants: "Variants",
    addVariant: "Add variant",
    variantId: "Variant id (default for one variant)",
    size: "Size",
    colour: "Colour",
    finish: "Finish",
    dims: "Width × height × depth (mm)",
    width: "Width",
    height: "Height",
    depth: "Depth",
    materials: "Materials (separated by ;)",
    gtin: "GTIN (optional)",
    pictures: "Pictures",
    picturesHelp: "JPEG or PNG, at least 512 px on the short side. The first picture is the thumbnail.",
    addPicture: "Add picture",
    remove: "Remove",
    geometry: "3D file",
    geometryHelp:
      "GLB (preferred), glTF, FBX, OBJ or a Truebex object (.tbxa), at most 100 MB and 500 000 triangles, at real size.",
    uploadGeometry: "Upload 3D file",
    uploading: "Uploading…",
    noGeometry: "No 3D file yet.",
    triangles: "triangles",
    measured: "Measures",
    pricedIn: "Priced in",
    notPriced: "No price yet",
    editPrices: "Edit prices and stock",
    removeVariant: "Remove variant",
    confirmRemoveVariant: "Remove this variant and its prices?",
    variantStatus: { active: "Active", discontinued: "Discontinued" } as Record<string, string>,
  },
  prices: {
    title: "Prices and stock",
    description:
      "One price list per region, in its own currency. Type prices in the main unit (1299.00); they are never rounded for you.",
    region: "Region",
    regionsTitle: "Regions you sell in",
    regionsHelp: "Turn a region on to give it a price list; the delivery fee and days are the defaults for new prices there.",
    sell: "Sell here",
    defaultFee: "Default delivery fee",
    daysMin: "Days from",
    daysMax: "to",
    saveRegions: "Save regions",
    product: "Product",
    variant: "Variant",
    price: "Price",
    inclTax: "Incl. tax",
    taxRate: "Tax %",
    deliveryFee: "Delivery",
    days: "Days",
    stock: "Stock",
    leadTime: "Lead time (days)",
    availability: "Availability",
    status: "In this region",
    notSold: "Not sold here",
    statuses: { active: "Sold", discontinued: "Discontinued", hidden: "Not sold" } as Record<string, string>,
    availabilityStates: {
      "": "From stock",
      in_stock: "In stock",
      low_stock: "Low stock",
      made_to_order: "Made to order",
      out_of_stock: "Out of stock",
      discontinued: "Discontinued",
    } as Record<string, string>,
    save: "Save changes",
    saving: "Saving…",
    saved: "Saved {n} rows.",
    unsaved: "{n} unsaved",
    discard: "Discard",
    invalid: "Some cells need fixing; nothing was saved.",
    bulk: "Selected",
    selectAll: "Select all",
    setStock: "Set stock",
    setStatus: "Set",
    adjust: "Change price by %",
    apply: "Apply",
    empty: "No variants yet. Add products in the catalogue or upload a spreadsheet.",
    noRegion: "You do not sell in any region yet. Turn one on below.",
  },
  imports: {
    title: "Imports",
    description:
      "Upload the spreadsheet template, a CSV or a JSON feed. A dry run shows what would change before anything is written.",
    template: "Download the spreadsheet template",
    templateHelp: "Sheets catalogue, help, categories and regions; one row per variant and region.",
    upload: "Upload a file",
    file: "XLSX, CSV or JSON, at most 50 MB and 100 000 rows",
    mode: "Mode",
    modes: {
      upsert: "Update: change only the rows in the file",
      replace: "Replace: the file is the whole catalogue; products it omits are hidden",
    } as Record<string, string>,
    check: "Check the file",
    checking: "Checking…",
    dryRun: "Dry run",
    summary: "{rows} rows · {created} created · {updated} updated · {unchanged} unchanged · {rejected} rejected",
    newItems: "{products} new products, {variants} new variants",
    hidden: "{n} products hidden (replace mode)",
    apply: "Apply",
    applying: "Importing…",
    applied: "Imported.",
    expired: "This dry run is more than 24 hours old. Upload the file again.",
    errors: "Rejected rows",
    warnings: "Warnings",
    row: "Row",
    column: "Column",
    code: "Problem",
    value: "Value",
    noErrors: "No rejected rows.",
    runs: "Past runs",
    noRuns: "No runs yet.",
    report: "Report",
    sources: { upload: "Feed upload", pull: "Daily feed", portal: "Portal", admin: "Truebex" } as Record<string, string>,
    runStates: { queued: "Queued", running: "Running", done: "Done", failed: "Failed" } as Record<string, string>,
    feedTitle: "Daily feed address",
    feedHelp: "An https address Truebex reads every day at 02:00 UTC. Use a full catalogue file in Replace mode.",
    feedUrl: "Address (https://…)",
    feedFormat: "Format",
    saveFeed: "Save address",
    removeFeed: "Remove",
    pullNow: "Read now",
    nextPull: "Next read",
    lastPull: "Last read",
    feedStatuses: {
      queued: "Read; an import was queued",
      not_modified: "Unchanged since the last read",
      failed: "Failed",
    } as Record<string, string>,
    keysHint: "Systems can also send files to the feed API with a supplier key (Team → Supplier keys).",
    codes: {
      missing_required: "A required column is empty.",
      too_long: "Over the length limit.",
      unknown_category: "Not a path of the categories sheet.",
      unknown_kind: "Not object, material, finish or theme.",
      unknown_region: "Not a region of the regions sheet.",
      currency_mismatch: "Not the region's currency (GBP for GB).",
      bad_price: "Not a number, a thousands separator, or more decimals than the currency has.",
      bad_bool: "Not true or false.",
      bad_integer: "Not a whole number.",
      bad_dims: "A dimension is missing, zero or implausible.",
      bad_url: "Not an https address.",
      bad_geometry_format: "Not GLB, glTF, FBX, OBJ or .tbxa.",
      geometry_fetch_failed: "The 3D file could not be downloaded.",
      image_fetch_failed: "The picture could not be downloaded.",
      image_too_small: "The picture is under 512 px.",
      duplicate_row: "The same SKU, variant and region twice.",
      bad_status: "Not active, discontinued or hidden.",
      bad_gtin: "Wrong length or check digit.",
      inconsistent_product: "Differs from the first row of the same SKU or variant.",
      bad_availability: "Not one of the four values, or made to order without a lead time.",
      unknown_column: "Not a column Truebex reads; ignored.",
      classification_ignored: "Not a uniclass, etim or gpc code; ignored.",
      looks_reformatted: "Looks changed by a spreadsheet program; format the column as text.",
      unknown_variant: "No such variant in your catalogue.",
    } as Record<string, string>,
  },
  inbox: {
    title: "Inbox",
    description:
      "Requests for quote and orders for your products. Buyer details are shown only on your own requests and orders.",
    filters: { open: "Open", quote: "Requests", order: "Orders", all: "All" } as Record<string, string>,
    empty: "Nothing here yet. Requests for quote and orders sent from Truebex appear here and by e-mail.",
    request: "Request for quote",
    order: "Order",
    buyer: "Buyer",
    deliveryTo: "Delivery to",
    message: "Message",
    project: "Project",
    lines: "Products",
    qty: "Qty",
    listed: "Listed",
    yourPrice: "Your price (each)",
    deliveryFee: "Delivery fee",
    daysMin: "Delivery from (days)",
    daysMax: "to (days)",
    validDays: "Quote valid for (days)",
    quoteMessage: "Message to the buyer",
    sendQuote: "Send quote",
    decline: "Decline",
    accept: "Accept",
    reject: "Reject",
    reason: "Reason (shown to the buyer)",
    carrier: "Carrier",
    reference: "Tracking reference",
    ship: "Mark shipped",
    deliver: "Mark delivered",
    total: "Total",
    paidOnTruebex: "Paid on Truebex",
    paidOffline: "You invoice the buyer",
    quotedAt: "Quoted",
    expires: "Expires",
    open: "Open",
    close: "Close",
    shippedWith: "Shipped with",
    states: {
      submitted: "New request",
      quoted: "Quoted",
      declined: "Declined",
      accepted: "Accepted",
      expired: "Expired",
      cancelled: "Cancelled by the buyer",
      pending: "To accept",
      rejected: "Rejected",
      shipped: "Shipped",
      delivered: "Delivered",
    } as Record<string, string>,
  },
  analytics: {
    title: "Analytics",
    description: "What designers look at and buy, per day and product. Counts only: no buyer is ever identified here.",
    from: "From",
    to: "To",
    region: "Region",
    allRegions: "All regions",
    last7: "7 days",
    last30: "30 days",
    last90: "90 days",
    metric: "Chart",
    metrics: {
      impressions: "Search impressions",
      views: "Product views",
      geometry_downloads: "Placements",
      quotes: "Requests for quote",
      orders: "Orders",
    } as Record<string, string>,
    orderValue: "Order value",
    product: "Product",
    empty: "No activity in this period.",
  },
  billing: {
    title: "Plan and billing",
    description: "Your listing plan, commission statements and payouts for orders.",
    plans: "Listing plan",
    plansNote: "Plan terms are still being set; these are the current terms.",
    current: "Current plan",
    choose: "Choose",
    commission: "Commission {pct} % of the goods value excluding tax and delivery",
    noFee: "No listing fee",
    perMonth: "a month",
    pending: "Recorded. Truebex invoices this plan until online payment opens.",
    statements: "Statements",
    noStatements: "No statements yet. A statement is made each month once orders are paid through Truebex.",
    month: "Month",
    orders: "Orders",
    commissionCol: "Commission",
    fee: "Listing fee",
    total: "Total",
    state: "State",
    invoice: "Invoice",
    statementStates: { pending: "To be invoiced", invoiced: "Invoiced" } as Record<string, string>,
    payouts: "Payouts for orders",
    payoutsText:
      "Orders paid on Truebex are paid out to your bank through Stripe, minus the commission, after you accept them. Until then buyers send you requests for quote.",
    connect: "Connect payouts",
    reconnect: "Continue payout setup",
    connected: "Payouts connected.",
    connecting: "Payout setup started; finish it on Stripe.",
    paymentsOff:
      "Card payments for orders are not open yet: buyers send requests for quote, and you invoice accepted quotes yourself.",
  },
  team: {
    title: "Team",
    description: "People who work on your catalogue and orders, and keys for your systems' feeds.",
    members: "Members",
    you: "you",
    role: "Role",
    remove: "Remove",
    confirmRemove: "Remove {email}? Their supplier keys stop working.",
    invite: "Invite by e-mail",
    email: "E-mail",
    send: "Send invitation",
    invited: "Invitation sent to {email}.",
    pending: "Invitations",
    expires: "expires",
    expired: "expired",
    revoke: "Revoke",
    keys: "Supplier keys",
    keysHelp:
      "A supplier key lets your system send catalogue feeds to Truebex (POST /market/feeds) for this supplier only. It is shown once.",
    keyName: "Key name, e.g. ERP export",
    createKey: "Create key",
    newKey: "Copy this key now; it is not shown again.",
    copy: "Copy",
    copied: "Copied",
    noKeys: "No supplier keys.",
    lastUsed: "last used",
    never: "never used",
    revoked: "revoked",
  },
  errors: {
    generic: "Something went wrong.",
  },
} as const;
